baseURL = 'https://ahanaftaskinarrafee.com'
languageCode = 'en-us'
title = "Taskin's site"
theme = 'chalk'
googleAnalytics = 'G-15CBJRDXXB'

[params.chalk]
	# chalk theme parameters
	about_enabled = true # Change to true if you wish to show an icon in the navigation that redirects to the about page
	scrollappear_enabled = false
	theme_toggle = false
	rss_enabled = true
	#blog_theme = 'light' # Doesn't matter if theme_toggle = true
	local_fonts = true
