baseURL = 'https://ahanaftaskinarrafee.com'
languageCode = 'en-gb'
title = "īeġ"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[outputs]
home = ["HTML", "RSS"]


[params]
  description = "īeġ, home to Taskin's personal ramblings"
  ogImage = "https://ahanaftaskinarrafee.com/Oilify.png"
  ogImagealt = "Oilified portrait of īeġ author and webmaster Taskin, with the subject unrecognisable"
  fediCreator = "@taskin@mastodon.social"

  [params.author]
    name = 'Ahanaf Taskin Ar-Rafee'
    email = 'ahanaftaskinarrafee@gmail.com'

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

enableRobotsTXT = true
robots = [  "AdsBot-Google", "Amazonbot", "anthropic-ai", "Applebot", "Applebot-Extended", "AwarioRssBot", "AwarioSmartBot", "Bytespider", "CCBot", "ChatGPT", "ChatGPT-User", "Claude-Web", "ClaudeBot", "cohere-ai", "DataForSeoBot", "Diffbot", "FacebookBot", "Google-Extended", "GPTBot", "ImagesiftBot", "magpie-crawler", "omgili", "Omgilibot", "peer39_crawler", "PerplexityBot", "YouBot" ]