baseURL = 'https://ahanaftaskinarrafee.com'
languageCode = 'en-gb'
title = "īeġ"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[outputs]
home = ["HTML", "RSS"]


[params]
  [params.author]
    name = 'Ahanaf Taskin Ar-Rafee'

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2