# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Build and Deploy Hugo Site with OpenRing

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["trial"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 'latest'
    steps:
      - name: Install Hugo CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y hugo

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          GO_VERSION: 'latest'
          
      - name: Build OpenRing
        run: |
          git clone https://git.sr.ht/~sircmpwn/openring
          cd openring
          go build -o openring
          sudo mv openring /usr/local/bin/

      - name: Generate Webring Output
        run: |
          /usr/local/bin/openring \
            -s https://www.calishat.com/feed \
            -s https://daringfireball.net/feeds/main \
            -s https://drewdevault.com/blog/index.xml \
            -s https://decoded.legal/blog/index.xml \
            -s https://emersion.fr/blog/rss.xml \
            -s https://neilzone.co.uk/index.xml \
            -s https://www.404media.co/rss \
            -s https://www.techdirt.com/feed \
            -s https://sifted.eu/feed?post_type=article \
            -s https://restofworld.org/feed/latest \
            -s https://uniquehazards.com/feed.xml \
            -s https://annoying.technology/index.xml \
            -s https://hacks.mozilla.org/feed/ \
            -s https://www.phoronix.com/rss.php \
            < ./webring-in.template \
            > ./layouts/partials/webring-out.html

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
